apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metadefender-menlo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metadefender-menlo
  minReplicas: 12
  maxReplicas: 18
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75